<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorizenetAuthAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorizenetAuthAccessRepository extends EntityRepository
{
    /**
     * @param int    $filter
     * @param string $orderBy
     * @param string $orderDirection
     * @return \Doctrine\ORM\Query
     */
    public function filter($filter, $orderBy, $orderDirection ) {
        $qb = $this->createQueryBuilder('auth');

        $qb->where($qb->expr()->isNotNull('auth.id'));

        if (!empty($filter)) {
            $qb->andWhere(
                $qb->expr()->orX(
                    $qb->expr()->like('auth.id', ':filter')
                )
            )->setParameter('filter', '%'.$filter.'%');
        }

        switch (strtolower($orderBy)) {
            case ('user'):
                // $qb->orderBy('auth.user_id', $orderDirection);
                break;
            default:
                // $qb->orderBy('auth.id', $orderDirection);
        }
        $qb->orderBy('auth.id', $orderDirection);

        return $qb->getQuery();
    }

    /**
     * @return mixed
     */
    public function getCount($filter = null)
    {
        $qb = $this
            ->createQueryBuilder('auth');

        $qb->where($qb->expr()->isNotNull('auth.id'));

        if (!empty($filter)) {
            $qb->andWhere(
                $qb->expr()->orX(
                    $qb->expr()->like('auth.id', ':filter')
                )
            )->setParameter('filter', '%'.$filter.'%');
        }

        return $qb
            ->select('count(auth.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}